Solved: Add rosetta (interpeter) #300
breck7/pldb pull request #304
Opened 2022-11-10 21:35 UTC by adriantintpilver

Create rosetta-2 pldb

2022-11-10 23:22 UTC, breck7 commented on database/things/rosetta-2.pldb
> + related dynamic binary translator
this line is causing the test failure.

2022-11-10 23:23 UTC, breck7 requested changes
looks good! just please fix the failing test (probably just remove that "related" line. the related line must contain only permalinks to other PLDB entries)

2022-11-11 12:12 UTC, adriantintpilver commented
Thanks Breck, has can't found the line with error and It was driving me crazy :-D
In addition add a "What Is Rosetta 2 And How to Install It on M1 Mac" link in documentation.

2022-11-11 14:02 UTC, merged

2022-11-11 14:02 UTC, breck7 commented
Great work @adriantintpilver !